version: '3.8'

services:
  app:
    build: .
    image: forum:latest 
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-db:/var/lib/sqlite3

volumes:
  sqlite-db: